id: I2180D346
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:19:23.436254+00:00
last_modified: 2022-12-14 18:19:23.436260+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-09-26T08:40:02.862Z'
  creationid: mabja
  eft-text-id: UT22084-072-037
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_337-Wheel_of_Dharma-v1
bases:
  D929:
    source_metadata: null
    order: 1
    base_file: D929.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
